#!/usr/bin/env python3
"""Rebuild source-of-truth inventory; never infer verification from test names."""
import hashlib, json, pathlib, re, subprocess, xml.etree.ElementTree as ET
ROOT = pathlib.Path(__file__).resolve().parents[1]
source = ROOT / 'spec/Invariant_Fabric_SRS_and_System_Architecture.md'
rows=[]
for number,line in enumerate(source.read_text().splitlines(),1):
    parts=[p.strip() for p in line.split('|')]
    if len(parts)>=5 and re.fullmatch(r'(?:[A-Z]{2,3}|NFR-[A-Z]+)-\d{3}',parts[1]):
        rows.append(dict(id=parts[1],requirement=parts[2],minimum_acceptance=parts[3],source_line=number))
assert len({r['id'] for r in rows})==len(rows)
# Deliberately independent of the legacy hard-coded traceability status arrays.
proof_file=ROOT/'reports/requirement-evidence.json'
proof=json.loads(proof_file.read_text()) if proof_file.exists() else {}
for r in rows:
    candidates=[]
    for f in sorted((ROOT/'tests').glob('*.test.mjs')):
        for line in f.read_text().splitlines():
            if r['id'] in line and re.search(r'\btest\(',line): candidates.append({'file':str(f.relative_to(ROOT)),'declaration':line.strip()})
    r.update(implementation=[],tests=candidates,verification_evidence=[],status='PARTIAL' if candidates else 'NOT_IMPLEMENTED',blocker_reason=None,remaining_work='Inspect complete semantics and execute positive/negative acceptance evidence; candidate test names are not proof.')
    if r['id'] in proof:
        r.update(proof[r['id']])
        if r['status']=='VERIFIED':
            valid=bool(r['implementation']) and bool(r['verification_evidence'])
            for ev in r['verification_evidence']:
                file=ROOT/ev['result_file']
                valid=valid and file.is_file() and hashlib.sha256(file.read_bytes()).hexdigest()==ev['result_sha256']
                valid=valid and all((ROOT/p).is_file() and hashlib.sha256((ROOT/p).read_bytes()).hexdigest()==h for p,h in ev['source_hashes'].items())
                if file.is_file():
                    cases=ET.parse(file).findall('.//testcase')
                    passed={c.attrib['name'] for c in cases if c.find('failure') is None and c.find('error') is None and c.find('skipped') is None}
                    valid=valid and bool(ev['passing_test_names']) and set(ev['passing_test_names'])<=passed
            if not valid:r.update(status='PARTIAL',remaining_work='Previously reviewed proof is stale or missing; rerun mapped executable verification before closure.')
current_path=ROOT/'reports/evidence/current-verification.json'
current=json.loads(current_path.read_text()) if current_path.exists() else {}
ci_path=ROOT/'reports/evidence/github-ci.json'
ci=json.loads(ci_path.read_text()) if ci_path.exists() else {}
counts={s:sum(r['status']==s for r in rows) for s in ['VERIFIED','PARTIAL','NOT_IMPLEMENTED','BLOCKED_EXTERNAL']}
state={'baseline_sha':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'total_requirements':len(rows),**counts,'failing_tests':current.get('failing_tests',[]),'baseline_tests':{'passed':98,'failed':0,'command':'node --test --test-concurrency=1 tests/*.test.mjs','evidence':'reports/baseline-tests.tap'},'current_verification':{k:current.get(k) for k in ['source_revision','passed','failed','skipped','pass']},'ci_state':ci if ci else 'NOT_VERIFIED_FOR_CURRENT_REVISION','performance_state':'NOT_VERIFIED_FOR_FINAL_REVISION','additional_contracts':'Sections 3–5 and 8–14 must also be covered; numbered requirement count is not a waiver.','last_completed_requirement':next((r['id'] for r in reversed(rows) if r['status']=='VERIFIED'),None),'next_action':next((r['id']+': '+r['remaining_work'] for r in rows if r['status'] not in ['VERIFIED','BLOCKED_EXTERNAL']),'Final clean-checkout gate'),'requirements':rows}
(ROOT/'reports/completion-state.json').write_text(json.dumps(state,indent=2,ensure_ascii=False)+'\n')
lines=['# SRS completion ledger','','Generated by `python scripts/completion-ledger.py` directly from the supplied SRS. Candidate test references do not establish verification. Baseline source: `'+state['baseline_sha']+'`.','',json.dumps(counts),'','| ID | Status | Requirement | Evidence / remaining work |','|---|---|---|---|']
for r in rows:lines.append('| '+r['id']+' | '+r['status']+' | '+r['requirement'].replace('|',' / ')+' | '+(json.dumps(r['verification_evidence']) if r['status']=='VERIFIED' else r['remaining_work']).replace('|',' / ')+' |')
(ROOT/'docs/COMPLETION_LEDGER.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({k:v for k,v in state.items() if k!='requirements'}))
